# Generated by Django 3.0.5 on 2020-04-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0003_auto_20200416_1847'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
